prompt Importing table LFRisk...
set feedback off
set define off
insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10099000', '2002', '幸福住院费用补偿医疗保险', 'H', 'M', 'S', '1', '3', '1', '1', null, '0', null, null, '01', '1', null, '1', '1', null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10164000', '2002', '幸福安心住院津贴医疗保险', 'H', 'M', 'S', '1', '3', '1', '3', null, null, null, null, '01', '1', null, '1', '1', null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10165000', '2002', '幸福安心住院费用补偿医疗保险（A）', 'H', 'M', 'S', '1', '3', '1', '1', null, '0', null, null, '01', '1', null, '1', '1', null, null, null);

prompt Done.
