prompt Importing table LMDutyGetClm...
set feedback off
set define off
insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('099040', '住院费用保险金', '100', null, '099060', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('099040', '住院费用保险金', '200', null, '099060', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 30, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('099041', '住院费用保险金', '100', null, '099060', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('099041', '住院费用保险金', '200', null, '099060', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 30, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('099042', '住院前、后门急诊费用保险金', '100', null, '099061', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('099042', '住院前、后门急诊费用保险金', '200', null, '099061', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 30, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('164040', '一般住院日额保险金', '108', null, '164050', null, null, '2', 'YL', null, null, null, null, null, null, null, null, null, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('164040', '一般住院日额保险金', '208', null, '164052', null, null, '2', 'YL', null, null, null, null, null, null, null, null, 30, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('164041', '重大疾病住院日额保险金', '208', null, '164054', null, null, '2', 'YL', null, null, null, null, null, null, null, null, 90, null, null, '1', null, null, '164056', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('164041', '重大疾病住院日额保险金', '108', null, '164054', null, null, '2', 'YL', null, null, null, null, null, null, null, null, null, null, null, '1', null, null, '164056', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165040', '住院费用保险金', '100', null, '165040', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165040', '住院费用保险金', '200', null, '165040', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 30, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165041', '住院费用保险金无理赔优惠', '100', null, '165046', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, '165070', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165041', '住院费用保险金无理赔优惠', '200', null, '165046', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 30, null, null, '1', null, null, '165070', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165042', '住院前、后门急诊费用保险金', '100', null, '165042', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165042', '住院前、后门急诊费用保险金', '200', null, '165042', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', null, '165046', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, '165071', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', null, '165046', null, null, '2', 'YL', null, '000', null, null, null, null, null, null, 0, null, null, '1', null, null, '165071', null);

prompt Done.
