prompt Importing table LMDutyPay...
set feedback off
set define off
insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('099020', '住院费用保险金', '0', 0, 'Y', null, 'S', '3', null, '099000', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('099021', '住院费用保险金+住院前、后门急诊费用保险金', '0', 0, 'Y', null, 'S', '3', null, '099000', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('164020', '幸福安心住院津贴医疗保险缴费', '0', 0, 'Y', 1000, 'S', '3', null, '164001', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('165020', '幸福安心A款住院费用补偿医疗保险缴费', '0', 0, 'Y', null, 'S', '3', null, '165000', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

prompt Done.
