prompt Importing table LMDutyGetFeeRela...
set feedback off
set define off
insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCR', '床位费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCO', '其它-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCM', '药费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCE', '检查费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCC', '治疗费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCT', '化验费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '200', 'BCA', '账单总金额', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCO', '其它-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCM', '药费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCE', '检查费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCA', '账单总金额', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCC', '治疗费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCT', '化验费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099040', '住院费用保险金', '100', 'BCR', '床位费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCT', '化验费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCA', '账单总金额', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCA', '账单总金额', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCT', '化验费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCR', '床位费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCO', '其它-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCM', '药费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCE', '检查费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '100', 'BCC', '治疗费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCC', '治疗费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCE', '检查费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCM', '药费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCR', '床位费-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099041', '住院费用保险金', '200', 'BCO', '其它-不细分', '02', '099051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACT', '化验费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACR', '床位费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACO', '其它-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACM', '药费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACE', '检查费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACC', '治疗费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '100', 'ACA', '账单总金额', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACA', '账单总金额', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACC', '治疗费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACE', '检查费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACM', '药费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACO', '其它-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACR', '床位费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('099042', '住院前、后门急诊费用保险金', '200', 'ACT', '化验费-不细分', '02', '099050', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164040', '住院日额保险金', '208', 'PP001', '疾病住院日额津贴', '02', '164053', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164040', '住院日额保险金', '108', 'PP001', '意外住院日额津贴', '02', '164051', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA028', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA029', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA029', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA030', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA030', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA001', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA001', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA002', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA002', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA003', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA003', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA004', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA004', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA005', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA005', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA006', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA006', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA007', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA007', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA008', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA008', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA009', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA009', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA010', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA010', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA011', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA011', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA012', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA012', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA013', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA013', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA014', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA014', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA015', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA015', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA016', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA016', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA017', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA017', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA018', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA018', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA019', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA019', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA020', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA020', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA021', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA021', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA022', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA022', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA023', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA023', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA024', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA024', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA025', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA025', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA026', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA026', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA027', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '208', 'PA027', '疾病重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('164041', '重大疾病住院日额保险金', '108', 'PA028', '意外重大疾病住院日额津贴', '02', '164055', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCT', '化验费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCR', '床位费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCO', '其它-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCM', '药费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCE', '检查费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCC', '治疗费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCA', '账单总金额', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCA', '账单总金额', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCT', '化验费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCR', '床位费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCO', '其它-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCM', '药费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '100', 'BCE', '检查费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165040', '住院费用保险金', '200', 'BCC', '治疗费-不细分', '02', '165041', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCT', '化验费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCR', '床位费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCO', '其它-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCM', '药费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCE', '检查费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCC', '治疗费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCA', '账单总金额', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCT', '化验费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCR', '床位费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCO', '其它-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCM', '药费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCE', '检查费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '100', 'BCC', '治疗费-不细分', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165041', '住院费用保险金无理赔优惠', '200', 'BCA', '账单总金额', '02', '165044', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACC', '治疗费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACE', '检查费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACA', '账单总金额', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACT', '化验费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACR', '床位费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACO', '其它-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACM', '药费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACE', '检查费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '200', 'ACC', '治疗费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACA', '账单总金额', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACT', '化验费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACR', '床位费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACO', '其它-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165042', '住院前、后门急诊费用保险金', '100', 'ACM', '药费-不细分', '02', '165043', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACC', '治疗费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACT', '化验费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACR', '床位费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACO', '其它-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACM', '药费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACE', '检查费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACA', '账单总金额', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACA', '账单总金额', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACT', '化验费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACR', '床位费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACO', '其它-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACM', '药费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '100', 'ACE', '检查费-不细分', '02', '165045', null);

insert into LMDutyGetFeeRela (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, CLMFEECODE, CLMFEENAME, CLMFEECALTYPE, CLMFEECALCODE, CLMFEEDEFVALUE)
values ('165043', '住院前、后门急诊费用保险金无理赔优惠', '200', 'ACC', '治疗费-不细分', '02', '165045', null);

prompt Done.
