prompt Importing table LMRiskPay...
set feedback off
set define off
insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10099000', '2002', '幸福住院费用补偿医疗保险', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10164000', '2002', '幸福安心住院津贴医疗保险', 'Y', null, null, null, null, null, null, null, 60, 'D', null);

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10165000', '2002', '幸福安心A款住院费用补偿医疗保险', 'N', null, null, null, null, null, null, null, 60, 'D', '0');

prompt Done.
