prompt Importing table LMRiskRole...
set feedback off
set define off
insert into LMRiskRole (RISKCODE, RISKVER, RISKROLE, RISKROLESEX, RISKROLENO, MINAPPAGEFLAG, MINAPPAGE, MAXAPPAGEFLAG, MAXAPPAGE)
values ('10099000', '2002', '01', '2', '01', 'D', 30, 'Y', 55);

insert into LMRiskRole (RISKCODE, RISKVER, RISKROLE, RISKROLESEX, RISKROLENO, MINAPPAGEFLAG, MINAPPAGE, MAXAPPAGEFLAG, MAXAPPAGE)
values ('10164000', '2002', '01', '2', '01', 'D', 30, 'Y', 55);

insert into LMRiskRole (RISKCODE, RISKVER, RISKROLE, RISKROLESEX, RISKROLENO, MINAPPAGEFLAG, MINAPPAGE, MAXAPPAGEFLAG, MAXAPPAGE)
values ('10165000', '2002', '01', '2', '01', 'D', 30, 'Y', 55);

prompt Done.
