prompt Importing table LFRisk...
set feedback off
set define off
insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10162000', '2002', '幸福人生终身重大疾病保险', 'H', 'L', 'M', '1', '1', '2', '3', null, null, null, null, null, '1', null, null, '1', null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10183000', '2002', '幸福百万安心保两全保险', 'L', 'L', 'M', '1', '2', '2', null, null, null, null, null, '01', '1', null, null, null, null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10197000', '2002', '幸福鑫悦一生B款终身年金保险（分红型）', 'L', 'L', 'M', '2', '1', '2', null, null, '0', null, null, '01', '1', null, null, null, null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10199000', '2002', '幸福稳盈一生年金保险（万能型）', 'L', 'L', 'M', '4', '4', '2', null, null, null, null, null, '01', '1', null, null, null, null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10208000', '2002', '幸福附加投保人豁免保险费定期寿险', 'L', 'L', 'S', '1', '3', '2', null, null, '0', null, null, '1', '1', null, '1', null, null, '2', null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10210000', '2002', '幸福附加两全保险', 'L', 'L', 'S', '1', '2', '2', null, null, '0', null, null, '01', '1', null, null, null, null, '2', null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10212000', '2002', '幸福传世金生终身寿险', 'L', 'L', 'M', '1', '1', '2', null, null, null, null, null, null, '1', null, null, '1', null, null, null);

insert into LFRisk (RISKCODE, RISKVER, RISKNAME, RISKTYPE, RISKPERIOD, SUBRISKFLAG, LIFETYPE, RISKDUTYTYPE, RISKYEARTYPE, HEALTHTYPE, ACCIDENTTYPE, ENDOWMENTFLAG, ENDOWMENTTYPE1, ENDOWMENTTYPE2, RISKSALECHNL, RISKGRPFLAG, CHARGESALECHNL, TREATTYPE, HEALTHTYPE2, SPECIALLIST, ISREVENUEFLAG, ISYLGET)
values ('10215000', '2002', '幸福健康人生尊享版重大疾病保险', 'H', 'L', 'M', '1', '1', '2', '3', null, '0', null, null, '01', '1', null, null, '1', null, null, null);

prompt Done.
