prompt Importing table LMDutyGetClm...
set feedback off
set define off
insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162040', '重大疾病保险金', '104', null, '162019', null, null, null, 'YL', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162040', '重大疾病保险金', '204', null, '162018', null, null, null, 'YL', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162041', '身故保险金', '202', null, '162018', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162041', '身故保险金', '102', null, '162019', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162042', '全残保险金', '103', null, '162019', null, null, null, 'SC', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162042', '全残保险金', '203', null, '162018', null, null, null, 'SC', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162043', '疾病终末期保险金', '204', null, '162018', null, null, null, null, null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162043', '疾病终末期保险金', '104', null, '162019', null, null, null, null, null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162044', '早期治疗保险金', '104', null, '162020', null, null, null, null, null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '162022', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162044', '早期治疗保险金', '204', null, '162021', null, null, null, null, null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '162022', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162045', '早期治疗豁免保险费', '209', null, null, null, '162024', null, null, null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '162025', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('162045', '早期治疗豁免保险费', '109', null, null, null, '162024', null, null, null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '162022', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183040', '疾病身故或全残保险金', '202', null, '183008', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183040', '疾病身故或全残保险金', '203', null, '183008', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183041', '一般意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183041', '一般意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183042', '自驾车意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183042', '自驾车意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183043', '水陆公共交通工具意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183043', '水陆公共交通工具意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183044', '航空公共交通工具意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183044', '航空公共交通工具意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183045', '高铁意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183045', '高铁意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183046', '重大自然灾害意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183046', '重大自然灾害意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183047', '电梯意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183047', '电梯意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183048', '法定节假日意外身故或全残保险金', '102', null, '183009', null, null, null, 'SW', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('183048', '法定节假日意外身故或全残保险金', '103', null, '183009', null, null, null, 'SC', null, '003', null, null, null, null, null, null, 180, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('197040', '疾病身故保险金', '202', null, '197018', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('197040', '意外身故保险金', '102', null, '197018', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('199041', '意外身故保险金', '102', null, '199012', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('199041', '疾病身故保险金', '202', null, '199012', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('208040', '疾病死亡赔付', '202', null, '208042', null, null, null, null, null, '008', null, null, null, null, null, null, null, null, null, null, '000000', null, '208044', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('208040', '疾病豁免', '209', null, null, null, null, null, null, null, '008', null, null, null, null, null, null, null, null, null, null, '000000', null, '208041', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('208040', '意外豁免', '109', null, null, null, null, null, null, null, '008', null, null, null, null, null, null, null, null, null, null, '000000', null, '208040', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('208040', '疾病全残赔付', '203', null, '208042', null, null, null, null, null, '008', null, null, null, null, null, null, null, null, null, null, '000000', null, '208043', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('210040', '身故或身体全残保险金', '102', null, '210004', null, null, null, 'SW', null, '008', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('210040', '身故或身体全残保险金', '203', null, '210025', null, null, null, 'SC', null, '008', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('210040', '身故或身体全残保险金', '103', null, '210004', null, null, null, 'SC', null, '008', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('210040', '身故或身体全残保险金', '202', null, '210025', null, null, null, 'SW', null, '008', null, null, null, null, null, null, 0, null, null, '1', null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('212040', '身故保险金', '202', null, '212019', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('212040', '身故保险金', '102', null, '212018', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('212041', '身体全残保险金', '203', null, '212019', null, null, null, 'SC', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('212041', '身体全残保险金', '103', null, '212018', null, null, null, 'SC', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215040', '轻症疾病保险金', '204', null, '215005', null, null, null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215011', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215040', '轻症疾病保险金', '104', null, '215005', null, null, null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215011', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215041', '中症疾病保险金', '204', null, '215042', null, null, null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215043', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215041', '中症疾病保险金', '104', null, '215042', null, null, null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215043', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215042', '重大疾病保险金', '104', null, '215006', null, null, null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215012', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215042', '重大疾病保险金', '204', null, '215006', null, null, null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215012', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215043', '疾病终末期保险金', '204', null, '215007', null, null, null, 'YL', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, '215013', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215043', '疾病终末期保险金', '104', null, '215007', null, null, null, 'YL', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, '215013', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215044', '身故保险金', '202', null, '215017', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, '215014', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215044', '身故保险金', '102', null, '215017', null, null, null, 'SW', null, '008', null, null, null, null, null, null, null, null, null, null, null, null, '215014', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215045', '轻症疾病豁免保险费', '209', null, null, null, '215016', null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215008', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215045', '轻症疾病豁免保险费', '109', null, null, null, '215016', null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215008', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215046', '中症疾病豁免保险费', '209', null, null, null, '215016', null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215046', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215046', '中症疾病豁免保险费', '109', null, null, null, '215016', null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215046', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215047', '重大疾病豁免保险费', '109', null, null, null, '215016', null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215009', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215047', '重大疾病豁免保险费', '209', null, null, null, '215016', null, 'YL', null, '000', null, null, null, null, null, null, null, null, null, null, null, null, '215009', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215048', '第二次恶性肿瘤保险金', '104', null, '215010', null, null, null, 'YL', null, '006', null, null, null, null, null, null, null, null, null, null, null, null, '215015', null);

insert into LMDutyGetClm (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, INPFLAG, STATTYPE, MINGET, AFTERGET, MAXGET, CLAIMRATE, CLMDAYLMT, SUMCLMDAYLMT, DEDUCTIBLE, DEDUCTDAY, OBSPERIOD, DEADVALIFLAG, DEADTOPVALUEFLAG, NEEDRECOMPUTE, CASEPOLTYPE, DEFORMITYGRADE, FILTERCALCODE, EFFECTONMAINRISK)
values ('215048', '第二次恶性肿瘤保险金', '204', null, '215010', null, null, null, 'YL', null, '006', null, null, null, null, null, null, null, null, null, null, null, null, '215015', null);

prompt Done.
