prompt Importing table LMDutyPay...
set feedback off
set define off
insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('162020', '幸福人生终身重大疾病保险缴费', '0', 12, 'Y', null, 'S', '0', null, '162001', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('183020', '幸福百万安心保两全保险责任缴费', '0', 12, 'Y', null, 'S', '0', null, '183000', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'Y', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('197020', '幸福鑫悦一生B款终身年金保险（分红型）缴费', '0', 12, 'Y', null, 'S', '0', null, null, '197000', null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '1', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('199020', '幸福稳盈一生年金保险（万能型）责任缴费', '0', 0, 'Y', null, 'S', '3', null, null, '199000', null, null, null, null, null, '0', 'N', 'N', 'N', null, 'N', null, null, 'Y', '1', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('208020', '幸福附加投保人豁免保险费定期寿险交费', '0', 12, 'Y', null, 'S', '3', null, '208000', null, null, null, null, null, null, '0', 'Y', 'N', 'N', 'N', 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('210020', '幸福附加两全保险交费', '0', 12, 'Y', null, 'S', '0', null, '210000', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('212020', '幸福传世金生终身寿险缴费', '0', null, 'Y', null, 'S', '0', null, '212001', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('215020', '健康人生尊享版重大疾病缴费', '0', 12, 'Y', null, 'S', '0', null, '215001', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

insert into LMDutyPay (PAYPLANCODE, PAYPLANNAME, TYPE, PAYINTV, PAYENDYEARFLAG, PAYENDYEAR, PAYENDDATECALREF, PAYENDDATECALMODE, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, RATE, MINPAY, ASSUYIELD, FEERATE, PAYTODATECALMODE, URGEPAYFLAG, PAYLACKFLAG, PAYOVERFLAG, PAYOVERDEAL, AVOIDPAYFLAG, GRACEPERIOD, PUBFLAG, ZEROFLAG, NEEDACC, PAYAIMCLASS, FIXEDRATECALCODE)
values ('215021', '健康人生尊享版重大疾病缴费(含可选责任)', '0', 12, 'Y', null, 'S', '0', null, '215001', null, null, null, null, null, null, '0', 'Y', 'N', 'N', null, 'N', null, null, 'N', '0', '1', null);

prompt Done.
