prompt Importing table LMDuty...
set feedback off
set define off
insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('162000', '幸福人生终身重大疾病保险责任', null, 'Y', null, null, 0, 'Y', 1000, 'Y', null, null, 'G', '0', '4', '4', '000003', null, '1', 1000.00, '01', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('183000', '幸福百万安心保两全保险责任', null, 'Y', 'S', '0', 0, 'Y', null, 'Y', null, null, 'G', '0', '3', '0', '183001', null, '1', 10000.00, '00', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('197000', '幸福鑫悦一生B款终身年金保险（分红型）责任', null, 'Y', 'S', '0', 0, 'Y', 1000, 'Y', null, null, 'P', '0', '4', '4', '000003', null, '4', 1.00, '00', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('199000', '幸福稳盈一生年金保险（万能型）责任', null, 'Y', 'S', null, 0, 'Y', null, 'Y', null, null, 'I', '3', '4', '0', '000003', null, '4', 1.00, '90', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('208000', '幸福附加投保人豁免保险费定期寿险', null, null, 'S', '3', 0, 'Y', null, null, null, null, 'G', '3', '4', '0', '000003', null, '1', 100.00, '30', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('210000', '幸福附加两全保险', null, 'Y', 'S', '3', 0, 'Y', null, null, null, null, 'G', '0', '0', '0', '210002', null, '1', 1000.00, '00', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('212000', '幸福传世金生终身寿险责任', null, 'Y', null, null, 0, 'Y', 1000, 'Y', null, null, 'G', '0', '4', '4', '000003', null, '1', 1000.00, '03', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('215000', '健康人生尊享版重大疾病', null, null, 'S', '0', 0, 'Y', null, null, null, null, 'G', '0', '4', '0', '215000', null, '1', 1000.00, '03', '0');

insert into LMDuty (DUTYCODE, DUTYNAME, PAYENDYEAR, PAYENDYEARFLAG, PAYENDDATECALREF, PAYENDDATECALMODE, GETYEAR, GETYEARFLAG, INSUYEAR, INSUYEARFLAG, ACCIYEAR, ACCIYEARFLAG, CALMODE, PAYENDYEARRELA, GETYEARRELA, INSUYEARRELA, BASICCALCODE, RISKCALCODE, AMNTFLAG, VPU, ADDFEEFLAG, ENDDATECALMODE)
values ('215001', '健康人生尊享版重大疾病(含可选责任)', null, null, 'S', '0', 0, 'Y', null, null, null, null, 'G', '0', '4', '0', '215000', null, '1', 1000.00, '03', '0');

prompt Done.
