prompt Importing table LMDutyGetAlive...
set feedback off
set define off
insert into LMDutyGetAlive (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, GETINTV, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, GETSTARTPERIOD, GETSTARTUNIT, STARTDATECALREF, STARTDATECALMODE, MINGETSTARTPERIOD, GETENDPERIOD, GETENDUNIT, ENDDATECALREF, ENDDATECALMODE, MAXGETENDPERIOD, ADDFLAG, ADDINTV, ADDSTARTPERIOD, ADDSTARTUNIT, ADDENDPERIOD, ADDENDUNIT, ADDTYPE, ADDVALUE, MAXGETCOUNT, AFTERGET, GETACTIONTYPE, URGEGETFLAG, DISCNTFLAG, GETCOND, MAXGETCOUNTTYPE, NEEDRECOMPUTE)
values ('183049', '满期保险金', '1', 0, null, null, '183010', null, null, 'Y', 'S', '3', null, null, null, 'S', '3', null, 'N', null, null, null, null, null, null, null, null, '003', '1', 'Y', null, null, null, '1');

insert into LMDutyGetAlive (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, GETINTV, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, GETSTARTPERIOD, GETSTARTUNIT, STARTDATECALREF, STARTDATECALMODE, MINGETSTARTPERIOD, GETENDPERIOD, GETENDUNIT, ENDDATECALREF, ENDDATECALMODE, MAXGETENDPERIOD, ADDFLAG, ADDINTV, ADDSTARTPERIOD, ADDSTARTUNIT, ADDENDPERIOD, ADDENDUNIT, ADDTYPE, ADDVALUE, MAXGETCOUNT, AFTERGET, GETACTIONTYPE, URGEGETFLAG, DISCNTFLAG, GETCOND, MAXGETCOUNTTYPE, NEEDRECOMPUTE)
values ('197041', '关爱金', '1', null, null, '197013', null, null, 5, 'Y', 'S', '0', null, 5, 'Y', 'S', '0', null, 'N', null, null, null, null, null, null, null, null, '000', '1', 'Y', null, null, null, '1');

insert into LMDutyGetAlive (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, GETINTV, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, GETSTARTPERIOD, GETSTARTUNIT, STARTDATECALREF, STARTDATECALMODE, MINGETSTARTPERIOD, GETENDPERIOD, GETENDUNIT, ENDDATECALREF, ENDDATECALMODE, MAXGETENDPERIOD, ADDFLAG, ADDINTV, ADDSTARTPERIOD, ADDSTARTUNIT, ADDENDPERIOD, ADDENDUNIT, ADDTYPE, ADDVALUE, MAXGETCOUNT, AFTERGET, GETACTIONTYPE, URGEGETFLAG, DISCNTFLAG, GETCOND, MAXGETCOUNTTYPE, NEEDRECOMPUTE)
values ('197042', '年金', '2', 12, null, '197002', null, null, 6, 'Y', 'S', '0', null, null, 'Y', 'S', '3', null, 'N', null, null, null, null, null, null, null, null, '000', '1', 'Y', null, null, null, '1');

insert into LMDutyGetAlive (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, GETINTV, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, GETSTARTPERIOD, GETSTARTUNIT, STARTDATECALREF, STARTDATECALMODE, MINGETSTARTPERIOD, GETENDPERIOD, GETENDUNIT, ENDDATECALREF, ENDDATECALMODE, MAXGETENDPERIOD, ADDFLAG, ADDINTV, ADDSTARTPERIOD, ADDSTARTUNIT, ADDENDPERIOD, ADDENDUNIT, ADDTYPE, ADDVALUE, MAXGETCOUNT, AFTERGET, GETACTIONTYPE, URGEGETFLAG, DISCNTFLAG, GETCOND, MAXGETCOUNTTYPE, NEEDRECOMPUTE)
values ('199040', '年金', '1', 12, null, '199017', null, null, 5, 'Y', 'S', '0', null, null, null, 'S', '3', null, 'N', null, null, null, null, null, null, null, null, '000', '1', 'Y', null, null, null, '1');

insert into LMDutyGetAlive (GETDUTYCODE, GETDUTYNAME, GETDUTYKIND, GETINTV, DEFAULTVAL, CALCODE, CNTERCALCODE, OTHCALCODE, GETSTARTPERIOD, GETSTARTUNIT, STARTDATECALREF, STARTDATECALMODE, MINGETSTARTPERIOD, GETENDPERIOD, GETENDUNIT, ENDDATECALREF, ENDDATECALMODE, MAXGETENDPERIOD, ADDFLAG, ADDINTV, ADDSTARTPERIOD, ADDSTARTUNIT, ADDENDPERIOD, ADDENDUNIT, ADDTYPE, ADDVALUE, MAXGETCOUNT, AFTERGET, GETACTIONTYPE, URGEGETFLAG, DISCNTFLAG, GETCOND, MAXGETCOUNTTYPE, NEEDRECOMPUTE)
values ('210041', '生存金', '1', 0, null, '210002', null, null, -1, 'A', 'S', '0', null, null, 'Y', 'C', '0', null, 'N', null, null, null, null, null, null, null, null, '000', '1', 'Y', null, null, null, '1');

prompt Done.
