prompt Importing table LMEdorWT...
set feedback off
set define off
insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10162000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10183000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10197000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10199000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10208000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10210000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10212000', '2002', 'Y', 'D', 0, 15);

insert into LMEdorWT (RISKCODE, RISKVERSION, HESITATEFLAG, HESITATETYPE, HESITATESTART, HESITATEEND)
values ('10215000', '2002', 'Y', 'D', 0, 15);

prompt Done.
