prompt Importing table LMRisk...
set feedback off
set define off
insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10162000', '2002', '幸福人生终身重大疾病保险', '幸福人生终身重疾', null, null, 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'N', null, '10162000', null, '幸福人生终身重大疾病保险');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10183000', '2002', '幸福百万安心保两全保险', '幸福百万安心保两全保险', null, null, 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', null, null, null, '幸福百万安心保两全保险');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10197000', '2002', '幸福鑫悦一生B款终身年金保险（分红型）', '幸福鑫悦一生B款终身年金保险（分红型）', null, null, 'N', 'Y', 'Y', 'Y', 'N', 'Y', 'N', 'Y', null, null, null, '幸福鑫悦一生B款终身年金保险（分红型）');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10199000', '2002', '幸福稳盈一生年金保险（万能型）', '幸福稳盈一生年金保险（万能型）', null, null, 'N', 'N', 'Y', 'Y', 'N', 'Y', 'N', 'Y', null, null, null, '幸福稳盈一生年金保险（万能型）');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10208000', '2002', '幸福附加投保人豁免保险费定期寿险', '幸福附加投保人豁免保险费定期寿险', null, null, 'N', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', null, '10208000', null, '幸福附加投保人豁免保险费定期寿险');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10210000', '2002', '幸福附加两全保险', '附加两全保险', null, null, 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', null, '10210000', null, '幸福附加两全保险');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10212000', '2002', '幸福传世金生终身寿险', '传世金生终身寿险', null, null, 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N', 'N', null, '10212000', null, '幸福传世金生终身寿险');

insert into LMRisk (RISKCODE, RISKVER, RISKNAME, RISKSHORTNAME, RISKENNAME, RISKENSHORTNAME, CHODUTYFLAG, CPAYFLAG, GETFLAG, EDORFLAG, RNEWFLAG, UWFLAG, RINSFLAG, INSUACCFLAG, DESTRATE, ORIGRISKCODE, SUBRISKVER, RISKSTATNAME)
values ('10215000', '2002', '幸福健康人生尊享版重大疾病保险', '健康人生尊享版重大疾病', null, null, 'Y', 'N', 'N', 'Y', 'N', 'Y', 'N', 'N', null, '10215000', null, '幸福健康人生尊享版重大疾病保险');

prompt Done.
