prompt Importing table LMRiskAccPay...
set feedback off
set define off
insert into LMRiskAccPay (RISKCODE, RISKVER, INSUACCNO, DEFAULTRATE, NEEDINPUT, ACCCREATEPOS, CALCODEMONEY, CALCODEUNIT, CALFLAG, PAYPLANCODE, PAYPLANNAME, PAYNEEDTOACC, RISKACCPAYNAME, PAYPLANTYPE)
values ('10197000', '2002', '197000', 0, '0', '1', null, null, '1', '197020', '幸福鑫悦一生B款终身年金保险（分红型）缴费', '1', null, null);

insert into LMRiskAccPay (RISKCODE, RISKVER, INSUACCNO, DEFAULTRATE, NEEDINPUT, ACCCREATEPOS, CALCODEMONEY, CALCODEUNIT, CALFLAG, PAYPLANCODE, PAYPLANNAME, PAYNEEDTOACC, RISKACCPAYNAME, PAYPLANTYPE)
values ('10197000', '2002', '197001', 0, '0', '1', null, null, '1', '197020', '幸福鑫悦一生B款终身年金保险（分红型）缴费', '1', null, null);

insert into LMRiskAccPay (RISKCODE, RISKVER, INSUACCNO, DEFAULTRATE, NEEDINPUT, ACCCREATEPOS, CALCODEMONEY, CALCODEUNIT, CALFLAG, PAYPLANCODE, PAYPLANNAME, PAYNEEDTOACC, RISKACCPAYNAME, PAYPLANTYPE)
values ('10197000', '2002', '197002', 0, '0', '3', null, null, '1', '197020', '幸福鑫悦一生B款终身年金保险（分红型）缴费', '1', null, null);

insert into LMRiskAccPay (RISKCODE, RISKVER, INSUACCNO, DEFAULTRATE, NEEDINPUT, ACCCREATEPOS, CALCODEMONEY, CALCODEUNIT, CALFLAG, PAYPLANCODE, PAYPLANNAME, PAYNEEDTOACC, RISKACCPAYNAME, PAYPLANTYPE)
values ('10199000', '2002', '199000', 1, '0', '1', null, null, '1', '199020', '稳盈一生年金保险（万能型）缴费', '1', '稳盈一生年金保险（万能型）缴费', null);

prompt Done.
