prompt Importing table LMRiskPay...
set feedback off
set define off
insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10162000', '2002', '幸福人生终身重大疾病保险', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10183000', '2002', '幸福百万安心保两全保险', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10197000', '2002', '幸福鑫悦一生B款终身年金保险（分红型）', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10199000', '2002', '幸福稳盈一生年金保险（万能型）', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10208000', '2002', '幸福附加投保人豁免保险费定期寿险', 'Y', null, null, null, null, null, null, null, 60, 'D', null);

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10210000', '2002', '幸福附加两全保险', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10212000', '2002', '幸福传世金生终身寿险', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

insert into LMRiskPay (RISKCODE, RISKVER, RISKNAME, URGEPAYFLAG, CHARGETYPE, CUTPAYINTV, PAYAVOIDTYPE, CHARGEANDPREM, BALADATETYPE, PAYAVOIDFLAG, PAYANDREVEFFE, GRACEPERIOD, GRACEPERIODUNIT, GRACEDATECALMODE)
values ('10215000', '2002', '幸福健康人生尊享版重大疾病保险', 'Y', null, null, null, null, null, null, null, 60, 'D', '0');

prompt Done.
